# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8b291b37-9e7d-49fb-8213-6de2c5d9affd";
      fsType = "ext4";
    };

  fileSystems."/home/miscguy/sync" =
    { device = "sync";
      fsType = "virtiofs";
    };

  fileSystems."/home/miscguy/github" =
    { device = "github";
      fsType = "virtiofs";
    };

  fileSystems."/home/miscguy/OneDrive" =
    { device = "OneDrive";
      fsType = "virtiofs";
    };

  fileSystems."/home/miscguy/Downloads" =
    { device = "Downloads";
      fsType = "virtiofs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/6edffa20-a9b8-434d-8e0a-de09f5689e69"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
