#! /bin/sh

su -c "flatpak update -y" miscguy
nix-channel --update
nixos-rebuild switch
retval=$?
if [ $retval == 0 ]; then
  pushd /home/miscguy/nixos
  gennbr="$(nix-env --list-generations -p /nix/var/nix/profiles/system | grep current | awk '{print $1}')"
  msg="$HOSTNAME: generation $gennbr"
  su -c "git pull" miscguy
  su -c "git add ." miscguy
  su -c "git commit -m \"$msg\"" miscguy
  su -c "git push" miscguy
  popd
fi
