#! /bin/sh

nixos-rebuild switch
retval=$?
if [ $retval == 0 ]; then
  gennbr="$(nix-env --list-generations -p /nix/var/nix/profiles/system | grep current | awk '{print $1}')"
  msg="$HOSTNAME: generation $gennbr"
  git add .
  git commit -m "$msg"
  git push
fi
